version: '3'
services: 
  postgres:
    image: 'postgres:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /src/node_modules/
      - ./server:/src
    environment: 
      - PGUSER=$DOCKER_PGUSER
      - PGHOST=$DOCKER_PGHOST
      - PGDATABASE=$DOCKER_PGDATABASE
      - PGPASSWORD=$DOCKER_PGPASSWORD
      - PGPORT=5432
      - JWSECRET=$DOCKER_JWSECRET
      - ADMIN_EMAIL=$DOCKER_ADMIN_EMAIL
      - ADMIN_PASSWORD=$DOCKER_ADMIN_PASSWORD
      - ADMIN_SECRET=$DOCKER_ADMIN_SECRET
    expose:
      - '5000'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /src/node_modules/
      - ./client:/src
    environment: 
      - REACT_APP_ADMIN_EMAIL=$DOCKER_ADMIN_EMAIL
      - REACT_APP_ADMIN_PASSWORD=$DOCKER_ADMIN_PASSWORD
      - REACT_APP_ADMIN_SECRET=$DOCKER_ADMIN_SECRET
    expose:
      - '3000'