DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS photos CASCADE;
DROP TABLE IF EXISTS user_photo CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE photos (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_on DATE NOT NULL DEFAULT CURRENT_DATE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(255),
  photo VARCHAR(255) NOT NULL
);

CREATE TABLE user_photo (
  user_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE, photo_id INTEGER REFERENCES photos(id) ON UPDATE CASCADE ON DELETE CASCADE, 
  amount     numeric NOT NULL DEFAULT 0,
  CONSTRAINT user_photo_pkey PRIMARY KEY (user_id, photo_id)  -- explicit pk
);